### ISSUE TITLE
PF2, terrain not respected

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk108/enhanced-terrain-layer#100]
Tested with Culrpit, only Drag Ruler (Traumi V10), Drag Ruler PF2 Integration, Terrain Ruler 1.7.0, Enhanced Terrain Layer

1. Draw a region x2 with ETL 10.1
2. Move token over the region -- see there's no respect for the difficult terrain.

![image](https://user-images.githubusercontent.com/4083812/192271617-0a8e14c6-49c5-4583-ace2-f799675e69a5.png)

Testing a X/Y coordinate inside the zone

canvas.terrain.cost({x: 1400, y: 1200})
terrainlayer.js:278 Uncaught TypeError: terrainInfo.shape.contains is not a function
[Detected 1 package: enhanced-terrain-layer]
    at TerrainLayer.costWithTerrain (terrainlayer.js:278:40)
    at TerrainLayer.cost (terrainlayer.js:305:21)
    at <anonymous>:1:16

**Comment by apoapostolov** [comment]
This issue is still present in 10.2

**Comment by apoapostolov** [comment]
Based on suggestion from Avery on Discord, colprit test without DR using raw measurement tool, same issue.

![image](https://user-images.githubusercontent.com/4083812/192332090-27740b16-2a59-4f35-bc28-5b71c7d27d98.png)

**Comment by apoapostolov** [comment]
I can confirm this is fixed in 10.3
